CREATE TABLE products (
    id VARCHAR(36) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    img VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);